/* 
 _______ ___ ___ _______ ______ _______ _______ _______ ______ 
|       |   |   |    ___|   __ \     __|    ___|    ___|   __ \
|   -   |   |   |    ___|      <__     |    ___|    ___|      <
|_______|\_____/|_______|___|__|_______|_______|_______|___|__|

  Overseer — Blank Page Games
  File: UnityLogBridge.cs
  Description: Bridges Unity's built-in logging system to the Overseer log store.
  Unity: 2022.3+ (also compatible with Unity 6 / 6.2)
  .NET: .NET Standard 2.1
  License:
    Copyright (c) 2025 Blank Page Games
    Permission is granted to use, modify, and distribute this software in personal or commercial projects.
    However, you may not sell, sublicense, or redistribute the software itself or any modified version as a standalone product.

  This file is part of the 'Overseer' asset by Blank Page Games.
*/

using UnityEngine;

namespace BPG.Overseer.Diagnostics
{
    /// <summary>
    /// A Unity <see cref="MonoBehaviour"/> that forwards Unity's native log messages
    /// (<see cref="Application.logMessageReceivedThreaded"/>) into the Overseer <see cref="LogStore"/>.
    /// </summary>
    /// <remarks>
    /// This ensures that all Unity console messages, including those generated by external systems,
    /// are captured and available within Overseer's logging pipeline.
    /// </remarks>
    [DefaultExecutionOrder(-10000)]
    public sealed class UnityLogBridge : MonoBehaviour
    {
        /// <summary>
        /// Subscribes to Unity's threaded log message callback when this component is enabled.
        /// </summary>
        private void OnEnable()
        {
            Application.logMessageReceivedThreaded += Handle;
        }

        /// <summary>
        /// Unsubscribes from Unity's threaded log message callback when this component is disabled.
        /// </summary>
        private void OnDisable()
        {
            Application.logMessageReceivedThreaded -= Handle;
        }

        /// <summary>
        /// Handles Unity log messages and converts them into <see cref="LogEntry"/> instances
        /// for storage in the <see cref="LogStore"/>.
        /// </summary>
        /// <param name="condition">The log message text.</param>
        /// <param name="stackTrace">The stack trace string, if provided.</param>
        /// <param name="type">The Unity log type associated with this message.</param>
        private void Handle(string condition, string stackTrace, LogType type)
        {
            var level = type switch
            {
                LogType.Error => LogLevel.Error,
                LogType.Assert => LogLevel.Error,
                LogType.Exception => LogLevel.Error,
                LogType.Warning => LogLevel.Warning,
                _ => LogLevel.Info
            };

            LogStore.Instance.Add(new LogEntry
            {
                TimeUtc = System.DateTime.UtcNow,
                Level = level,
                Channel = LogChannel.All, // Source unknown -> treat as global.
                Message = condition,
                StackTrace = stackTrace,
                ThreadName = System.Threading.Thread.CurrentThread.Name ?? "Thread",
                ContextName = string.Empty
            });
        }
    }
}
